spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8021

logging:
  file:
    name: logs/angjavaproject.log
    path: angjavaproject
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























